import { Star } from "@mui/icons-material";

const data = [
    {   id: 1,
        img: "https://th.bing.com/th/id/OIP.U2WjyWIhCCN6-JuTIYozlgHaHa?pid=ImgDet&rs=1",
        title: "Nike Flyknit",
        reviews: "(123 reviews)",
        newPrice: "160",
        company: "Nike",
        color: "red",
        category: "sneakers",
    },
    {   id: 2,
        img: "https://i8.amplience.net/i/jpl/jd_FX5354_a?qlt=92",
        title: "Adidas Galaxy 6WS",
        reviews: "(123 reviews)",
        newPrice: "80",
        company: "Adidas",
        color: "red",
        category: "sneakers",
    },
    {   id: 3,
        img: "https://img.eobuwie.cloud/eob_product_512w_512h(0/6/b/9/06b908eb8eb0c9697c8f31cb80f88a12aeb73147_01_0000300399637_rz.jpg,webp)/obuvki-adidas-terrex-free-hiker-2-gz0680-black.webp\n",
        title: "Adidas Terrex",
        reviews: "(123 reviews)",
        newPrice: "320",
        company: "Adidas",
        color: "black",
        category: "sneakers",
    },
    {   id: 4,
        img: "https://img.eobuwie.cloud/eob_product_1800w_1800h(0/4/d/3/04d3cce8f6ec6e75b92fe6b3341576ba0c4cc35e_02_4066762564729_mf.jpg,webp)/obuvki-adidas-bounce-legends-shoes-ie9278-carbon-goldmt-cblack-0000302550821.webp\n",
        title: "Adidas Bounce MS",
        reviews: "(123 reviews)",
        newPrice: "140",
        company: "Adidas",
        color: "black",
        category: "sneakers",
    },
    {   id: 5,
        img: "https://www.borutoku.com/images/shoes/nike%20shoes-060kro.jpg",
        title: "Nike Maroon X",
        reviews: "(123 reviews)",
        prevPrice: "$280",
        newPrice: "220      ",
        company: "Nike",
        color: "blue",
        category: "sneakers",
    },
    {   id: 6,
        img: "https://worthly.com/wp-content/uploads/2014/11/139517568.jpg",
        title: "Nike Knitted Shoe",
        reviews: "(123 reviews)",
        prevPrice: "$220,00",
        newPrice: "180",
        company: "Nike",
        color: "blue",
        category: "sneakers",
    },
    {   id: 7,
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Nike Air Monarch IV",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "49",
        company: "Nike",
        color: "white",
        category: "sneakers",
    },
    {   id: 8,
        img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
        title: "Nike Waffle One Sneaker",
        reviews: "(123 reviews)",
        prevPrice: "$340,00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "sneakers",
    },
    {   id: 9,
        img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
        title: "Nike Running Shoe",
        reviews: "(123 reviews)",
        prevPrice: "$279,00",
        newPrice: "200",
        company: "Adidas",
        color: "black",
        category: "sneakers",
    },
    {   id: 10,
        img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
        title: "Flat Slip On Pumps",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "green",
        category: "flats",
    },
    {   id: 11,
        img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
        title: "Knit Ballet Flat",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "flats",
    },

    {   id: 12,
        img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
        title: "Loafer Flats",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Vans",
        color: "white",
        category: "flats",
    },

    {   id: 13,
        img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
        title: "Nike Zoom Freak",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "sneakers",
    },

    {   id: 14,
        img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
        title: "Nike Men's Sneaker",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Adidas",
        color: "blue",
        category: "sneakers",
    },

    {   id: 15,
        img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        title: "PUMA BLACK-OCE",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Puma",
        color: "green",
        category: "sneakers",
    },
    {   id: 16,
        img: "https://media.screwfix.com/is/image/ae235/904JX_P?$fxSharpen$=&wid=257&hei=257&dpr=on",
        title: "Puma Xcite Metal",
        reviews: "(123 reviews)",
        newPrice: "150",
        company: "Puma",
        color: "blue",
        category: "sneakers",
    },
    {   id: 17,
        img: "https://www.redrat.co.nz/content/products/puma-softride-enzo-evolve-shoe-high-risk-redblackwhite-front-50047.jpg?width=1024",
        title: "Puma Soft Ride",
        reviews: "(123 reviews)",
        newPrice: "239",
        company: "Puma",
        color: "red",
        category: "sneakers",
    },

    {   id: 18,
        img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
        title: "Pacer Future Sneaker",
        reviews: "(123 reviews)",
        newPrice: "150",
        company: "Puma",
        color: "red",
        category: "sneakers",
    },
    {   id: 19,
        img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
        title: "Unisex-Adult Super",
        reviews: "(123 reviews)",
        prevPrice: "$180,00",
        newPrice: "150",
        company: "Puma",
        color: "black",
        category: "sneakers",
    },
    {   id: 20,
        img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
        title: "Roma Basic Sneaker",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "120",
        company: "Puma",
        color: "white",
        category: "sneakers",
    },
    {   id: 21,
        img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
        title: "Pacer Future Doubleknit",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "120",
        company: "Puma",
        color: "black",
        category: "sneakers",
    },

    {   id: 22,
        img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        title: "Fusion Evo Golf Shoe",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Puma",
        color: "green",
        category: "sneakers",
    },
    {   id: 23,
        img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
        title: "Rainbow Chex Skate",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "red",
        category: "flats",
    },
    {   id: 24,
        img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
        title: "Low-Top Trainers",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "white",
        category: "sandals",
    },
    {   id: 25,
        img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
        title: "Vans Unisex Low-Top",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "blue",
        category: "sandals",
    },
    {   id: 26,
        img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
        title: "Classic Bandana Sneakers",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Nike",
        color: "black",
        category: "sandals",
    },
    {   id: 27,
        img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
        title: "Chunky High Heel",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Vans",
        color: "black",
        category: "heels",
    },
    {   id: 28,
        img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
        title: "Slip On Stiletto High Heel",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "puma",
        color: "black",
        category: "heels",
    },
    {   id: 29,
        img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
        title: "DREAM PAIRS Court Shoes",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "99",
        company: "Nike",
        color: "red",
        category: "heels",
    },
    {   id: 30,
        img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
        title: "Low Mid Block Heels",
        reviews: "(123 reviews)",
        prevPrice: "$240,00",
        newPrice: "200",
        company: "Nike",
        color: "black",
        category: "heels",
    },
    {   id: 31,
        img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
        title: "Amore Fashion Stilettos",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "110",
        company: "Adidas",
        color: "white",
        category: "heels",
    },
    {   id: 32,
        img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
        title: "Bridal Sandals Glitter",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "heels",
    },
    {   id: 33,
        img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
        title: "Wedding Prom Bridal",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "flats",
    },
];

export default data;
